### ISSUE TITLE
Logistic Regression:  the printing accept rate will always be 0 bcz of feature of torch 0.4.0

### ISSUE THREAD

**Issue by Clovis0070** [SherlockLiao/pytorch-beginner#10]
第二章，logistic regression 代码：
line 65 report warnning: 

`UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number`

this will cause an error in line 74:  the value of  `running_acc / (batch_size * i))` will always be 0 because it's a tensor devide a number, this operation is no longer supported in latest torch version.

One solution is to modify line 65, use tensor.item()
`running_acc += num_correct.data[0].item()`

**Comment by L1aoXingyu** [comment]
这是0.3的代码，0.4确实需要改一下
