### ISSUE TITLE
autoencoder

### ISSUE THREAD

**Issue by Hangwei12358** [SherlockLiao/pytorch-beginner#17]
请问08章的readme里面, encoder的图是如何得到的？以及图里的-1.5到1.5代表什么含义？谢谢！

**Comment by L1aoXingyu** [comment]
https://github.com/L1aoXingyu/code-of-learn-deep-learning-with-pytorch/blob/master/chapter6_GAN/autoencoder.ipynb
你可以仿照这里面来换一下，这里面是三维的feature，你如果用二维的feature，就是二维的图片，-1.5-1.5是feature (x, y) 中 x 和 y 的范围
