### ISSUE TITLE
浮点数计算的小bug

### ISSUE THREAD

**Issue by JoeLee2013** [SherlockLiao/pytorch-beginner#2]
Logistic_Regression.py和neural_network.py源代码里的都存在一个相同的浮点数计算的小bug：
eval_loss = 0 
eval_acc = 0
需要做一下修改，方式有两种：
1）方式一：
eval_loss = 0.0 
eval_acc = 0.0
2）方式二：
在源代码文件第一行，加上“from __future__ import division”

**Comment by L1aoXingyu** [comment]
你是用的python2还是python3呢

**Comment by JoeLee2013** [comment]
python 2.7

**Comment by L1aoXingyu** [comment]
python3 不会有浮点数问题，我会修改一下适配python2，谢谢
