### ISSUE TITLE
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR_04-Convolutional Neural Network

### ISSUE THREAD

**Issue by bluizh** [SherlockLiao/pytorch-beginner#7]
# pytorch环境(ubuntu16.04)
   使用anocoda上安装的pytorch
   cudatoolkit:    8.0-3                     
   cudnn:          7.0.5-cuda8.0_0  
   pytorch:        0.3.0-py35cuda8.0cudnn7.0_0

# 运行04,碰到关于cudnn的问题, 错误信息如下:
epoch 1

Traceback (most recent call last):
  File "convolution_network.py", line 76, in <module>
    out = model(img)
  File "/home/yjx/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "convolution_network.py", line 48, in forward
    out = self.conv(x)
  File "/home/yjx/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yjx/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/yjx/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yjx/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "/home/yjx/.conda/envs/pytorch/lib/python3.5/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

# 代码测试了自己的cuda和cudnn

CUDA TEST
import torch
x = torch.Tensor([1.0])
xx = x.cuda()
print(xx)
CUDNN TEST
from torch.backends import cudnn
print(cudnn.is_acceptable(xx))
~                                
显示是正常可用,

**Comment by L1aoXingyu** [comment]
好像是 cudnn 的问题，pytorch 不用自己装 cudnn，你装上cuda8，然后直接装 pytorch，cudnn会自动装上

**Comment by SherlockLiao** [comment]
看错误好像是 cudnn，pytorch 不需要装 cudnn，只需要装cuda，在安装pytorch 的时候会自动安好cudnn

**Comment by bluizh** [comment]
@SherlockLiao 嗯嗯 我直接用 "conda install pytorch torchvision " 安装的, 里面是包含了cudnn, 但却用不了, 后来我在caffe中也编译了下,发现使用cudnn时,也发现同样的问题,,我在想会不会电脑配置的原因(因为是用普通笔记本配的),
# CUDA的deviceQuery 
Device 0: "GeForce GT 740M"
  CUDA Driver Version / Runtime Version          9.0 / 8.0
  CUDA Capability Major/Minor version number:    3.5
  Total amount of global memory:                 2004 MBytes (2101542912 bytes)
  ( 2) Multiprocessors, (192) CUDA Cores/MP:     384 CUDA Cores
  GPU Max Clock rate:                            1032 MHz (1.03 GHz)
  Memory Clock rate:                             900 Mhz
  Memory Bus Width:                              64-bit
  L2 Cache Size:                                 524288 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = GeForce GT 740M
